# LIST AND TUPLE

'''
LIST
    LIST IS CHANGABLE
    LIST ACCEPT DUBLICATE VALUES
    LIST ORDERD AND INDEXED
'''

newlist = ['BMW','Audi','Tata','M']
print(newlist)

# APPEND ADD ONE NEW VALUE AT THE LAST OF LIST BYDEFAULT
newlist.append('Maruti')
print('\nADD NEW VALUE AT LAST USING APPEND => ',newlist)

# INSERT USE TO REPLACE VALUE OF LIST BEHALF OF INDEX POSTION
newlist.insert(0,'Mahendra')
print('\nREPLACE 1ST INDEX VALUE => ',newlist)

# REMOVE WORKS ON LIST VALUE NOT ON INDEX POSTIION
newlist.remove('Audi')
print('\nREMOVE ONE VALUE => ',newlist)

# POP IN DEFAULT CASE POP REMOVE LAST INDEX OF LIST
newlist.pop()
print('\nPOP LAST INDEX VALUE => ',newlist)
# POP ALSO REMOVE SPECIFIC INDEX VALUE BY INDEX POSTION
newlist.pop(1)
print('\nPOP LAST INDEX VALUE => ',newlist)

# DEL IT'S NOT A SUB METHOD OF LIST
# DEL REMOVE INDEX POSTION OF LIST OR REMOVE A FULL LIST AT ONCE
del newlist[2]
print('\nDELETE 2ND POSTION OF LIST => ',newlist)
# DEL - USE TO REMOVE FULL LSIT AT ONCE
# del newlist
# print('\nDLETE FULL LIST AT ONCE USING DEL => ',newlist)

# COPY - MAKE A DUBLICATE LIST STORE IN NEW VARIABLE
copylist = newlist.copy()

# CLEAR USE TO EMPTY THE LIST BUT NOT DELETE THE LIST VARABLE
newlist.clear()
print('\nCLEAR FULL LIST OR EMPTY THE LIST => ',newlist)

# CHECK COPY LIST VALUE AFTER CLEARING THE MAIN LIST
print('\nCOPYLIST VALUES => ',copylist)

# ALSO A WAY TO COPY A LIST BY USING LIST DATATYPE TO STORE IT IN ANOHTER VARIABLE
# JOIN MORE THAN ONE LIST USING CONCATANATION SIGN (+) LIKE = LIST1 + LIST2
# APPEND ALSO USE TO ADD ANOTHER LIST TO A LIST USING IT A SAME WAY
# EXTEND ALSO USE TO ADD 2 LIST
# CONSTRUCTER USE TO MAKE A LIST'S CONSTRUCT 

'''
ARRAY CASE FOR EXAMPLE ONLY:
    FIFO - FIRST IN FIRST OUT
    LIFO - LAST IN FIRST OUT

ARRAYVAULE = ARRAY(1,2,3,4,5)
OUTPUT:
    ARRAYVALUE:
        [0] = 1
        [1] = 2
        [2] = 3
        [3] = 4
        [4] = 5

    CASES:
        APPEND: ADD ONE NEW VALUE AT THE LAST OF ARRAY
        AFTER ADD NEW VALUE:
            EXAMPLE: 
                [5] = 6

'''

'''
HOME WORK
    UNDERSTAND SUBMETHODS OF LIST
    CREATE ONE LIST WITH 5 CAR BRAND NAMES AND ONE LIST WITH 5 CAR MODALS
    USING THESE 2 LIST PERFORM FOLLOWING WORKS:
        * ADD 2 LISTS USING CONCTANATION AND TYPE CONVERSTION AND EXPEND AND ALSO KNOW THE DIFFERENCE B/W THEM        
        * CLEAR FIRST LIST WITH COPY IT IN ANOTHER VARAIBLE
        * DEL COPYLIST 
    DIFFERENCE B/W CLEAR + DEL + REMOVE
    DEFFERENCE B/W APPEND + INSERT
    DEFFERENCE B/W POP AND REMOVE


NOTE:
    ABOUT INPUT IN PYTHON
'''