import connection as con

# FETCH ALL DATA FROM USER TABLE
con.mycursor.execute("SELECT * FROM education ORDER BY id DESC LIMIT 5") # DESC USE TO ORDER BY DESENDING ORDER

# FETCH ALL ROWS BY fetchall() . AND GET RESULT AS LIST
myresult = con.mycursor.fetchall()

# fetch one row by betchone()
# myresult = con.mycursor.fetchone(). AND GET RESULT AS TUPLE
print('\n Type: ',type(myresult))

# GET ALL DATA LINE BY LINE USING FOR LOOP
for x in myresult:
    print(x)


'''
HOME WORK
    ALL METHOD ARE PART OF ONE CLASS USER
    CREATE A FUNCTION WHERE PASS A VALUE BY USER INPUT AND IN FUNCTION SELECT THE ROW DATA BEHALF OF THAT USER INPUT DATA. LIKE: YOU SELECT DATA WHERE USERNAME="INPUT DATA"

    CREATE A FUNCTION WHERE PASS A VALUE BY USER INPUT AND IN FUNCTION SELECT THE ROW DATA BEHALF OF THAT USER INPUT DATA. LIKE: YOU SELECT DATA WHERE COURSE="INPUT DATA"

    CREATE UPDATE METHOD WHERE TO UPDATE USER DATA 
    CREATE DELETE METHOD
    JOIN 2 TABLES
'''